/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import keyboardtexture from "../../../../../assets/desktop/Textures/1055_albedo.jpg";
import pctexture from "../../../../../assets/desktop/Textures/1045_albedo.jpg";
import monitortexture from '../../../../../assets/desktop/Textures/1054_emissive.jpg';
import { useLoader } from 'react-three-fiber'
import * as THREE from 'three';
import { MaterialLoader } from "three";

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/desk.gltf')

  const [KeyboardTextture, PCtexture,Monitor] = 
  useLoader(THREE.TextureLoader, [keyboardtexture, pctexture, monitortexture ]);

  return (
    <group ref={group} {...props} dispose={null}>
      
      <mesh geometry={nodes.Desk_Desk.geometry} material={nodes.Desk_Desk.material} material-color="white"/>
      <mesh geometry={nodes.Desk_Desk_1.geometry} material={materials['1042']} />
      <mesh geometry={nodes.PantallasEscritorios1_PantallasEscritorios1.geometry} material={materials['1053']} />
      <mesh geometry={nodes.PantallasEscritorios1_PantallasEscritorios1_1.geometry} material={materials['1054']}material-color="black" normalMap={Monitor}/>
      <mesh geometry={nodes.PC.geometry} material={nodes.PC.material} map={PCtexture} />
      <mesh geometry={nodes.PC_Cable2.geometry} material={nodes.PC_Cable2.material} />
      <mesh geometry={nodes.Teclado_Teclado.geometry} material={nodes.Teclado_Teclado.material} map={KeyboardTextture} material-color="white"/>
      <mesh geometry={nodes.Teclado_Teclado_1.geometry} material={nodes.Teclado_Teclado_1.material} />
      <mesh geometry={nodes.Mouse.geometry} material={materials['1043']}  material-color={0xffffff } />
    </group>
  )
}

useGLTF.preload('/desk.gltf')
